### ISSUE TITLE
claude v3 support?

### ISSUE THREAD

**Issue by tribbloid** [yagil/ChatIDE#14]
all options are for claude v1.3 , would you like to add the SotA claude v3

**Comment by yagil** [comment]
@tribbloid I added support for newer claude here: https://github.com/yagil/ChatIDE/commit/b66f91ba8a19a20c899eb7d51bfd5d1467e3234c

You will need to build and install from source, did not yet push this to the extension marketplace

**Comment by tribbloid** [comment]
don't have npm :-D

**Comment by weoreference** [comment]
> @tribbloid I added support for newer claude here: [b66f91b](https://github.com/yagil/ChatIDE/commit/b66f91ba8a19a20c899eb7d51bfd5d1467e3234c)
> 
> You will need to build and install from source, did not yet push this to the extension marketplace

Please do publish to the extension marketplace, most users don’t know how to “build from source” (hence why we use AI). Thank you

**Comment by nbubis** [comment]
Can we add 3.5 Sonnet as well?

**Comment by dzcpy** [comment]
Please add Claude 3.5 support! It's the BEST model for programming. Thanks!

**Comment by yagil** [comment]
CI fails unexpectedly which prevents publishing to the store at the moment: https://github.com/yagil/ChatIDE/issues/21
